In [1]:
# import libraries
import pandas as pd
import numpy as np
import os

In [2]:
path=r'C:\Users\Günay\Documents\Instacart Basket Analysis'

In [3]:
# Define function
def add_num(x,y):
 sum=x+y
 return sum

In [4]:
# Apply function
add_num(9,11)

20

In [5]:
df_ords_prods_merged=pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_merged.pkl'))

In [6]:
df_ords_prods_merged

,order_id,user_id,eval_set,order_number,order_dow,order_time,days_since_prior_order,product_id,add_to_cart_order,reordered,split,_merge,product_name,aisle_id,department_id,prices,exists
0,1501582.0,2.0,prior,2.0,5.0,10.0,10.0,8479,3.0,0.0,19.0,both,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both
1,382106.0,235.0,prior,2.0,6.0,8.0,13.0,8479,3.0,1.0,2.0,both,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both
2,1264640.0,235.0,prior,8.0,3.0,2.0,17.0,8479,10.0,1.0,17.0,both,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both
3,909400.0,235.0,prior,20.0,5.0,10.0,25.0,8479,7.0,1.0,12.0,both,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both
4,1698838.0,352.0,prior,9.0,0.0,15.0,16.0,8479,13.0,1.0,9.0,both,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1993212,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49669,NaN,NaN,NaN,NaN,K Cup Dark Blend,100.0,21.0,4.7,right_only
1993213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49672,NaN,NaN,NaN,NaN,Cafe Mocha K-Cup Packs,26.0,7.0,6.5,right_only
1993214,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49684,NaN,NaN,NaN,NaN,"Vodka, Triple Distilled, Twist of Vanilla",124.0,5.0,5.3,right_only
1993215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49687,NaN,NaN,NaN,NaN,Smartblend Healthy Metabolism Dry Cat Food,41.0,8.0,4.7,right_only
1993216,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49688,NaN,NaN,NaN,NaN,Fresh Foaming Cleanser,73.0,11.0,13.5,right_only

## If-statement with user-defined function

In [7]:
# Define a function

In [8]:
def price_label(row):

  if row['prices'] <= 5:
    return 'Low-range product'
  elif (row['prices'] > 5) and (row['prices'] <= 15):
    return 'Mid-range product'
  elif row['prices'] > 15:
    return 'High range'
  else: return 'Not enough data'

In [9]:
# Apply the function

In [11]:
df_ords_prods_merged['price_range'] = df_ords_prods_merged.apply(price_label, axis=1)

In [13]:
df_ords_prods_merged['price_range'].value_counts(dropna=False)

Mid-range product    1342131
Low-range product     623551
High range             25702
Not enough data         1833
Name: price_range, dtype: int64

In [14]:
df_ords_prods_merged['prices'].max()

99999.0

## If-statement with .loc() function

In [15]:
df_ords_prods_merged.loc[df_ords_prods_merged['prices'] > 15, 'price_range_loc'] = 'High-range product'

In [17]:
df_ords_prods_merged.loc[(df_ords_prods_merged['prices'] <= 15) & (df_ords_prods_merged['prices'] > 5), 'price_range_loc'] = 'Mid-range product'

In [18]:
df_ords_prods_merged.loc[df_ords_prods_merged['prices'] <= 5, 'price_range_loc'] = 'Low-range product'

In [19]:
df_ords_prods_merged['price_range_loc'].value_counts(dropna=False)

Mid-range product     1342131
Low-range product      623551
High-range product      25702
NaN                      1833
Name: price_range_loc, dtype: int64

In [20]:
df_ords_prods_merged

,order_id,user_id,eval_set,order_number,order_dow,order_time,days_since_prior_order,product_id,add_to_cart_order,reordered,split,_merge,product_name,aisle_id,department_id,prices,exists,price_range,price_range_loc
0,1501582.0,2.0,prior,2.0,5.0,10.0,10.0,8479,3.0,0.0,19.0,both,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both,Low-range product,Low-range product
1,382106.0,235.0,prior,2.0,6.0,8.0,13.0,8479,3.0,1.0,2.0,both,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both,Low-range product,Low-range product
2,1264640.0,235.0,prior,8.0,3.0,2.0,17.0,8479,10.0,1.0,17.0,both,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both,Low-range product,Low-range product
3,909400.0,235.0,prior,20.0,5.0,10.0,25.0,8479,7.0,1.0,12.0,both,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both,Low-range product,Low-range product
4,1698838.0,352.0,prior,9.0,0.0,15.0,16.0,8479,13.0,1.0,9.0,both,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both,Low-range product,Low-range product
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1993212,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49669,NaN,NaN,NaN,NaN,K Cup Dark Blend,100.0,21.0,4.7,right_only,Low-range product,Low-range product
1993213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49672,NaN,NaN,NaN,NaN,Cafe Mocha K-Cup Packs,26.0,7.0,6.5,right_only,Mid-range product,Mid-range product
1993214,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49684,NaN,NaN,NaN,NaN,"Vodka, Triple Distilled, Twist of Vanilla",124.0,5.0,5.3,right_only,Mid-range product,Mid-range product
1993215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49687,NaN,NaN,NaN,NaN,Smartblend Healthy Metabolism Dry Cat Food,41.0,8.0,4.7,right_only,Low-range product,Low-range product
1993216,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49688,NaN,NaN,NaN,NaN,Fresh Foaming Cleanser,73.0,11.0,13.5,right_only,Mid-range product,Mid-range product

## If-statement with for-loops

In [21]:
df_ords_prods_merged['order_dow'].value_counts(dropna=False)

0.0    376046
1.0    347895
6.0    274622
5.0    258939
2.0    257988
3.0    235508
4.0    232100
NaN     10119
Name: order_dow, dtype: int64

In [22]:
result = []

for value in df_ords_prods_merged["order_dow"]:
  if value == 0:
    result.append("Busiest day")
  elif value == 4:
    result.append("Least busy")
  else:
    result.append("Regularly busy")

In [23]:
result

['Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Least busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Least busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Least busy',
 'Busiest day',
 'Regularly busy',
 'Least busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Least busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Least busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Busiest day',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Least busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Least busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Least busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Busiest day',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Busiest day',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Least busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Busiest day',
 'Busiest day',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Least busy',
 'Regularly busy',
 'Busiest day',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Busiest day',
 'Regularly busy',
 'Busiest day',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 ...]

In [24]:
df_ords_prods_merged['busiest_day']=result

In [25]:
df_ords_prods_merged

,order_id,user_id,eval_set,order_number,order_dow,order_time,days_since_prior_order,product_id,add_to_cart_order,reordered,split,_merge,product_name,aisle_id,department_id,prices,exists,price_range,price_range_loc,busiest_day
0,1501582.0,2.0,prior,2.0,5.0,10.0,10.0,8479,3.0,0.0,19.0,both,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both,Low-range product,Low-range product,Regularly busy
1,382106.0,235.0,prior,2.0,6.0,8.0,13.0,8479,3.0,1.0,2.0,both,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both,Low-range product,Low-range product,Regularly busy
2,1264640.0,235.0,prior,8.0,3.0,2.0,17.0,8479,10.0,1.0,17.0,both,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both,Low-range product,Low-range product,Regularly busy
3,909400.0,235.0,prior,20.0,5.0,10.0,25.0,8479,7.0,1.0,12.0,both,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both,Low-range product,Low-range product,Regularly busy
4,1698838.0,352.0,prior,9.0,0.0,15.0,16.0,8479,13.0,1.0,9.0,both,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both,Low-range product,Low-range product,Busiest day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1993212,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49669,NaN,NaN,NaN,NaN,K Cup Dark Blend,100.0,21.0,4.7,right_only,Low-range product,Low-range product,Regularly busy
1993213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49672,NaN,NaN,NaN,NaN,Cafe Mocha K-Cup Packs,26.0,7.0,6.5,right_only,Mid-range product,Mid-range product,Regularly busy
1993214,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49684,NaN,NaN,NaN,NaN,"Vodka, Triple Distilled, Twist of Vanilla",124.0,5.0,5.3,right_only,Mid-range product,Mid-range product,Regularly busy
1993215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49687,NaN,NaN,NaN,NaN,Smartblend Healthy Metabolism Dry Cat Food,41.0,8.0,4.7,right_only,Low-range product,Low-range product,Regularly busy
1993216,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49688,NaN,NaN,NaN,NaN,Fresh Foaming Cleanser,73.0,11.0,13.5,right_only,Mid-range product,Mid-range product,Regularly busy

In [26]:
df_ords_prods_merged['busiest_day'].value_counts(dropna=False)

Regularly busy    1385071
Busiest day        376046
Least busy         232100
Name: busiest_day, dtype: int64

# Step-2

In [67]:
df_ords_prods_merged['order_dow'].value_counts(dropna=False)

0.0    376046
1.0    347895
6.0    274622
5.0    258939
2.0    257988
3.0    235508
4.0    232100
NaN     10119
Name: order_dow, dtype: int64

In [70]:
def busiest_days(row):

  if row['order_dow'] <= 1:
    return 'Busiest days'
  elif row['order_dow'] == 2:
    return 'Regularly busy'
  elif (row['order_dow'] >= 3) and (row['order_dow'] < 5):
    return 'Least busy'
  elif row['order_dow'] >=5:
    return 'Regularly busy'
  else: return 'Not enough data'

In [72]:
df_ords_prods_merged['busiest_days'] = df_ords_prods_merged.apply(busiest_days, axis=1)

In [73]:
df_ords_prods_merged['busiest_days'].value_counts(dropna=False)

Regularly busy     791549
Busiest days       723941
Least busy         467608
Not enough data     10119
Name: busiest_days, dtype: int64

In [74]:
df_ords_prods_merged

,order_id,user_id,eval_set,order_number,order_dow,order_time,days_since_prior_order,product_id,add_to_cart_order,reordered,...,product_name,aisle_id,department_id,prices,exists,price_range,price_range_loc,busiest_day,busiest_days,Busiest_days
0,1501582.0,2.0,prior,2.0,5.0,10.0,10.0,8479,3.0,0.0,...,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both,Low-range product,Low-range product,Regularly busy,Regularly busy,NaN
1,382106.0,235.0,prior,2.0,6.0,8.0,13.0,8479,3.0,1.0,...,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both,Low-range product,Low-range product,Regularly busy,Regularly busy,NaN
2,1264640.0,235.0,prior,8.0,3.0,2.0,17.0,8479,10.0,1.0,...,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both,Low-range product,Low-range product,Regularly busy,Least busy,NaN
3,909400.0,235.0,prior,20.0,5.0,10.0,25.0,8479,7.0,1.0,...,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both,Low-range product,Low-range product,Regularly busy,Regularly busy,NaN
4,1698838.0,352.0,prior,9.0,0.0,15.0,16.0,8479,13.0,1.0,...,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both,Low-range product,Low-range product,Busiest day,Busiest days,Busiest days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1993212,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49669,NaN,NaN,...,K Cup Dark Blend,100.0,21.0,4.7,right_only,Low-range product,Low-range product,Regularly busy,Not enough data,NaN
1993213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49672,NaN,NaN,...,Cafe Mocha K-Cup Packs,26.0,7.0,6.5,right_only,Mid-range product,Mid-range product,Regularly busy,Not enough data,NaN
1993214,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49684,NaN,NaN,...,"Vodka, Triple Distilled, Twist of Vanilla",124.0,5.0,5.3,right_only,Mid-range product,Mid-range product,Regularly busy,Not enough data,NaN
1993215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49687,NaN,NaN,...,Smartblend Healthy Metabolism Dry Cat Food,41.0,8.0,4.7,right_only,Low-range product,Low-range product,Regularly busy,Not enough data,NaN
1993216,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49688,NaN,NaN,...,Fresh Foaming Cleanser,73.0,11.0,13.5,right_only,Mid-range product,Mid-range product,Regularly busy,Not enough data,NaN

# Step-4

In [77]:
df_ords_prods_merged['order_time'].value_counts(dropna=False)

10.0    169210
11.0    167359
13.0    164758
14.0    164749
15.0    161349
12.0    160830
16.0    153525
9.0     150924
17.0    127035
8.0     107252
18.0     98751
19.0     76329
20.0     59101
7.0      55828
21.0     49169
22.0     39076
23.0     24233
6.0      17575
0.0      13348
NaN      10119
1.0       6838
5.0       5229
2.0       4149
4.0       3407
3.0       3074
Name: order_time, dtype: int64

In [79]:
def busiest_period(row):

  if (row['order_time'] >= 9) and (row['order_time'] <=16):
    return 'Most orders'
  elif (row['order_time'] >= 7) and (row['order_time'] <=8):
    return 'Average orders'
  elif (row['order_time'] >= 17) and (row['order_time'] <= 22):
    return 'Average orders'
  elif (row['order_time'] <= 6):
    return 'Fewest orders'
  elif row['order_time'] == 23:
    return 'Fewest orders'
  else: return 'Not enough data'

In [80]:
df_ords_prods_merged['busiest_period_of_day'] = df_ords_prods_merged.apply(busiest_period, axis=1)

In [81]:
df_ords_prods_merged

,order_id,user_id,eval_set,order_number,order_dow,order_time,days_since_prior_order,product_id,add_to_cart_order,reordered,...,aisle_id,department_id,prices,exists,price_range,price_range_loc,busiest_day,busiest_days,Busiest_days,busiest_period_of_day
0,1501582.0,2.0,prior,2.0,5.0,10.0,10.0,8479,3.0,0.0,...,78.0,19.0,3.5,both,Low-range product,Low-range product,Regularly busy,Regularly busy,NaN,Most orders
1,382106.0,235.0,prior,2.0,6.0,8.0,13.0,8479,3.0,1.0,...,78.0,19.0,3.5,both,Low-range product,Low-range product,Regularly busy,Regularly busy,NaN,Average orders
2,1264640.0,235.0,prior,8.0,3.0,2.0,17.0,8479,10.0,1.0,...,78.0,19.0,3.5,both,Low-range product,Low-range product,Regularly busy,Least busy,NaN,Fewest orders
3,909400.0,235.0,prior,20.0,5.0,10.0,25.0,8479,7.0,1.0,...,78.0,19.0,3.5,both,Low-range product,Low-range product,Regularly busy,Regularly busy,NaN,Most orders
4,1698838.0,352.0,prior,9.0,0.0,15.0,16.0,8479,13.0,1.0,...,78.0,19.0,3.5,both,Low-range product,Low-range product,Busiest day,Busiest days,Busiest days,Most orders
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1993212,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49669,NaN,NaN,...,100.0,21.0,4.7,right_only,Low-range product,Low-range product,Regularly busy,Not enough data,NaN,Not enough data
1993213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49672,NaN,NaN,...,26.0,7.0,6.5,right_only,Mid-range product,Mid-range product,Regularly busy,Not enough data,NaN,Not enough data
1993214,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49684,NaN,NaN,...,124.0,5.0,5.3,right_only,Mid-range product,Mid-range product,Regularly busy,Not enough data,NaN,Not enough data
1993215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49687,NaN,NaN,...,41.0,8.0,4.7,right_only,Low-range product,Low-range product,Regularly busy,Not enough data,NaN,Not enough data
1993216,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49688,NaN,NaN,...,73.0,11.0,13.5,right_only,Mid-range product,Mid-range product,Regularly busy,Not enough data,NaN,Not enough data

In [82]:
df_ords_prods_merged['busiest_period_of_day'].value_counts(dropna=False)

Most orders        1292704
Average orders      612541
Fewest orders        77853
Not enough data      10119
Name: busiest_period_of_day, dtype: int64

In [88]:
# The column of Busiest_days was created mistakenly. To delete it;

In [86]:
del df_ords_prods_merged['Busiest_days']

In [87]:
df_ords_prods_merged

,order_id,user_id,eval_set,order_number,order_dow,order_time,days_since_prior_order,product_id,add_to_cart_order,reordered,...,product_name,aisle_id,department_id,prices,exists,price_range,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,1501582.0,2.0,prior,2.0,5.0,10.0,10.0,8479,3.0,0.0,...,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Most orders
1,382106.0,235.0,prior,2.0,6.0,8.0,13.0,8479,3.0,1.0,...,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Average orders
2,1264640.0,235.0,prior,8.0,3.0,2.0,17.0,8479,10.0,1.0,...,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both,Low-range product,Low-range product,Regularly busy,Least busy,Fewest orders
3,909400.0,235.0,prior,20.0,5.0,10.0,25.0,8479,7.0,1.0,...,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both,Low-range product,Low-range product,Regularly busy,Regularly busy,Most orders
4,1698838.0,352.0,prior,9.0,0.0,15.0,16.0,8479,13.0,1.0,...,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both,Low-range product,Low-range product,Busiest day,Busiest days,Most orders
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1993212,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49669,NaN,NaN,...,K Cup Dark Blend,100.0,21.0,4.7,right_only,Low-range product,Low-range product,Regularly busy,Not enough data,Not enough data
1993213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49672,NaN,NaN,...,Cafe Mocha K-Cup Packs,26.0,7.0,6.5,right_only,Mid-range product,Mid-range product,Regularly busy,Not enough data,Not enough data
1993214,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49684,NaN,NaN,...,"Vodka, Triple Distilled, Twist of Vanilla",124.0,5.0,5.3,right_only,Mid-range product,Mid-range product,Regularly busy,Not enough data,Not enough data
1993215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49687,NaN,NaN,...,Smartblend Healthy Metabolism Dry Cat Food,41.0,8.0,4.7,right_only,Low-range product,Low-range product,Regularly busy,Not enough data,Not enough data
1993216,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49688,NaN,NaN,...,Fresh Foaming Cleanser,73.0,11.0,13.5,right_only,Mid-range product,Mid-range product,Regularly busy,Not enough data,Not enough data

In [89]:
df_ords_prods_merged.to_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_merged2.pkl'))